src/Entity/FormuleSansChauffeur.php
<?php

namespace App\Entity;

use App\Repository\FormuleSansChauffeurRepository;
use Doctrine\ORM\Mapping as ORM;
#[ORM\Table("FORMULESANSCHAUFFEUR")]

#[ORM\Entity(repositoryClass: FormuleSansChauffeurRepository::class)]
class FormuleSansChauffeur
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $Duree = null;

    #[ORM\Column]
    private ?int $Nbkminclus = null;

    #[ORM\Column(length: 255)]
    private ?string $Libelle = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDuree(): ?int
    {
        return $this->Duree;
    }

    public function setDuree(int $Duree): self
    {
        $this->Duree = $Duree;

        return $this;
    }

    public function getNbkminclus(): ?int
    {
        return $this->Nbkminclus;
    }

    public function setNbKmInclus(int $Nbkminclus): self
    {
        $this->Nbkminclus = $Nbkminclus;

        return $this;
    }

    public function getLibelle(): ?string
    {
        return $this->Libelle;
    }

    public function setLibelle(string $Libelle): self
    {
        $this->Libelle = $Libelle;

        return $this;
    }
}

src/Controller/ChoixreservationController.php
<?php

namespace App\Controller;

use App\Entity\Modele;
use App\Entity\FormuleSansChauffeur;
use App\Entity\Vehicule;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ChoixreservationController extends AbstractController
{
    #[Route('/choixreservation/{id}', name: 'app_choixreservation')]
    public function index(ManagerRegistry $doctrine, $id): Response
    {

        $repoModele = $doctrine->getRepository(Modele::class);
        $leModele = $repoModele->find($id);

        $repoFormule = $doctrine->getRepository(FormuleSansChauffeur::class);
        $formules=[];
        foreach ($repoFormule->findAll() as $formule) {
            $formules[] = $formule;
        }

        return $this->render('choixreservation/index.html.twig', [
            "Modele" => $leModele, "lesFormules"=>$formules,
        ]);
    }
}

templates/choixreservation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Réservation
{% endblock %}
{% block body %}
	<div class="background">
		<div class="shape"></div>
		<div class="shape"></div>
	</div>
<form action="{{ path('app_reservationPOST') }}" method="POST">
	<h3>Réservation</h3>

	<p>Nom :
		{{ Modele.nom }}</p>
	<p>Tarif Km Supplementaire :
		{{ Modele.tarifkmsupplementaire }}</p>
	<p>Nombre de places :
		{{ Modele.nbplaces }}</p>
	<p>Vitesse Max :
		{{ Modele.vitessemax }}</p>
	<p>Description :
		{{ Modele.description }}</p>
</br>
<img src="{{ Modele.image }}" width="325px"/>

<p>Choisir la formule :</p></br>
<select>
{% for formule in lesFormules %}
	<option>{{formule.libelle}}</option>
{% endfor %}
</select>

<p>Choisir la date de départ :</p></br>

<input type="date" id="dateDepart" name="dateDepart">

{# Pour récupérer l'id du modèle choisi #}
<input type="hidden" id="idModele" name="idModele" value={{Modele.id}}>

<p>Choisir la date de retour :</p></br>
<input type="date" id="dateRetour" name="dateRetour"></br>

<button>Confirmer la reservation</button>

<a href="/">Annuler la reservation</a><br>
</span>
</form>
{% endblock %}